### ISSUE TITLE
Release 0.4.0?

### ISSUE THREAD

**Issue by danielcompton** [clj-commons/byte-streams#63]
What do you think about releasing 0.4.0 now with the namespace duplications? I'm working on some code with Java modules and this is one of the blockers.

I can probably do the release but wanted to check if it's ok.

**Comment by KingMob** [comment]
Ahh, that was back in July, wasn't it? OK, let me cut a release.

**Comment by KingMob** [comment]
Waitaminit, the namespace duplications have been available since 0.3.0. Are you using the old pre-`org.clj-commons` group coordinate? Other than some very minor doc changes, there's nothing that's not deployed already. ???

**Comment by KingMob** [comment]
@danielcompton Any updates?

**Comment by p-himik** [comment]
I'd love to see the duplications being removed actually. Just spend half a day debugging an issue where in the end it turned out that one of my dependencies required `byte-streams` while the other required `clj-commons.byte-streams`, thus making the `conversions` atom incompatible.

Getting rid of the duplications will make it into an error that should be obvious on how to fix it.

Alternatively, one of the duplicated namespaces could simply defer all of its functionality to the other namespace. Or at least all the state.

**Comment by KingMob** [comment]
From #aleph Slack:

> Sorry you had to go through that.

> We can't really remove the duplicate namespaces, but we can make one import the vars from the other, which should prevent this issue in the future.

> Fundamentally, single-segment namespaces are problematic, and are discouraged for good reason these days. We know they interfere with Graal, and there's certainly more lurking time bombs, because they violate the widespread assumption that a class will be in a package.

**Comment by KingMob** [comment]
Shouldn't be any lingering ns duplication issues as of 0.3.2. 

@danielcompton @p-himik Feel free to reopen if you have any concerns or issues.
